[build]
  builder = "dockerfile"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "yt-dlp -U --no-check-certificates > /dev/null 2>&1; npx tsx server.ts"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 5
  healthcheckPath = "/api/songs"
  healthcheckTimeout = 300

[[volumes]]
  mountPath = "/data"
